version: 2
machine:
  services:
    - docker
    - mysql

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.0-browsers
    steps:
      - checkout
      - run:
          - bundle install
          - bundle exec rspec

  build:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: |
          docker build -t oleville/voting:${CIRCLE_SHA1} .

  deploy:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker:
      - checkout
      - run: |
          echo "hello world"

workflows:
  version: 2
  general:
    jobs:
      - test
      - build:
          requires: [test]
      - deploy:
          context: global
          requires: [build]
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /^v.*/
